import { notFound } from "next/navigation";
import GridDetails from "./GridDetails";
import BottomDetails from "./components/bottomSection/bottomDetails";

export const metadata = {
  title: "PumpZilla | Token",
  description: "Generated by create next app",
};

const Page = async ({ params }) => {
  try {
    const response = await fetch(`${process.env.NEXT_PUBLIC_BASE_URL}/api/tokenOne?tokenAddress=${params.tokenAddress}`);

    if (!response.ok) {
      console.error(response.statusText);
      
      return notFound(); 
    }
    
    const contentType = response.headers.get("content-type");
    if (!contentType || !contentType.includes("application/json")) {
      console.log(contentType);
      return notFound();
    }

    const tokenData = await response.json();

    return (
      <main className="pt-24 pl-20 pr-4 pb-4 w-screen">
        <GridDetails tokenData={tokenData} />
        <BottomDetails/>
      </main>
    );
  } catch (error) {
    console.error("Error fetching token data:", error);
    // Handle different error types, such as network issues, unexpected formats, etc.
    return notFound();
  }
};

export default Page
