import { notFound } from "next/navigation";
import GridDetails from "./GridDetails";

export const metadata = {
  title: "PumpZilla - Token",
  description: "Generated by create next app",
};

const Page = async ({params}) => {
    const response = await fetch(`${process.env.NEXT_PUBLIC_BASE_URL}/api/tokenOne?tokenAddress=${params.tokenAddress}`)
    if(!response.ok) return notFound();
    const tokenData = await response.json();
    
  return (
    <main className=" pt-24 pl-20 pr-4 pb-4 h-[200dvh] w-screen">
    <GridDetails tokenData={tokenData}/>
    </main>
  )
}

export default Page
