import Image from "next/image";
import ScreenHome from "./components/home/ScreenHome";
import { LaunchPageWrapper } from "./components/launch/LaunchScreen";
import HomeToptokenItem from "./components/HomeToptokenItem";


export const metadata = {
  title: "PumpZilla",
  description: "Generated by create next app",
};

export default async function Home() {
  let tokens = [];
  let prices = [];

  try {
    // Fetch tokens and prices from your API
    const response = await fetch(`${process.env.NEXT_PUBLIC_BASE_URL}/api/tokens`);
    const priceResponse = await fetch(`${process.env.NEXT_PUBLIC_BASE_URL}/api/prices`);

    // Check if the responses are okay
    if (response.ok && priceResponse.ok) {
      tokens = await response.json();
      prices = await priceResponse.json();
    } else {
      console.log("Failed to fetch data:", response.statusText, priceResponse.statusText);
    }
  } catch (error) {
    console.log("Fetch failed:", error);
  }

  return (
    <main className=" w-full pt-20 pl-16 relative font-[family-name:var(--font-geist-sans)]">
<div id="HomeScreen" className=" w-full">
 <div className=" relative">
 <Image src={'/homepageTop.png'} alt="godzilla" width={1400} height={200} className=" w-full h-auto"/>
 <div className=" absolute z-10 top-1/2 -translate-y-1/2 right-4 h-[90%] aspect-[7/10]">
  <HomeToptokenItem data={tokens[0]}/>
 </div>
 </div>

  <ScreenHome tokens={tokens} prices={prices}/>
</div> 
  <LaunchPageWrapper/>
    </main>
  );
}
