import Image from "next/image";
import ScreenHome from "./components/home/ScreenHome";
import { LaunchPageWrapper } from "./components/launch/LaunchScreen";


export const metadata = {
  title: "PumpZilla",
  description: "Generated by create next app",
};

export default async function Home() {
  const response = await fetch(`${process.env.NEXT_PUBLIC_BASE_URL}/api/tokens`);
  const tokens = await response.json();

  return (
    <main className=" w-full pt-20 pl-16 relative font-[family-name:var(--font-geist-sans)]">
<div id="HomeScreen" className=" w-full">
  <Image src={'/homepageTop.png'} alt="godzilla" width={1400} height={200} className=" w-full h-auto"/>

  <ScreenHome tokens={tokens}/>
</div> 
  <LaunchPageWrapper/>
    </main>
  );
}
